site_name: MichanPedia
site_url: https://TU-USUARIO.github.io/NOMBRE-DEL-REPO/
repo_url: https://github.com/TU-USUARIO/NOMBRE-DEL-REPO/
repo_name: Editar en GitHub

theme:
  name: material
  language: es
  palette: 
    # Modo claro por defecto
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Modo oscuro
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - search.suggest      # Sugerencias mientras buscas
    - search.highlight    # Resaltar texto buscado
    - navigation.expand   # Menú expandido

markdown_extensions:
  - admonition            # Para notas de advertencia/info
  - attr_list             # Para añadir atributos