site_name: MichanPedia
site_url: https://jongt23.github.io/michanpedia/
repo_url: https://github.com/jongt23/michanpedia/
repo_name: michanpedia

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  language: es
  palette: 
    # Modo claro por defecto
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    # Modo oscuro
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - search.suggest      # Sugerencias mientras buscas
    - search.highlight    # Resaltar texto buscado
    - navigation.expand   # MenÃº expandido

markdown_extensions:
  - admonition            # Para notas de advertencia/info
  - attr_list             # Para aÃ±adir atributos

nav:
  - ğŸ  Inicio: index.md
  - ğŸ“š Diccionario: abecedario.md
  - ğŸ’¬ Frases Ãštiles: frases.md
  # - ğŸ“– Historias:
  #     - ğŸ–ï¸ Viaje a Ibiza: anecdotas/ibiza.md
  #     - â›·ï¸ La Nieve: anecdotas/nieve.md
